final listJurusanRaw = [
  'FK - Pendidikan Dokter',
  'FKG - Pendidikan Kedokteran Gigi',
  'FKM - Gizi',
  'FKM - Kesehatan dan Keselamatan Kerja',
  'FKM - Kesehatan Lingkungan',
  'FKM - Kesehatan Masyarakat',
  'FIK - Keperawatan',
  'FF - Farmasi',
  'FMIPA - Aktuaria',
  'FMIPA - Biologi',
  'FMIPA - Fisika',
  'FMIPA - Geofisika',
  'FMIPA - Geografi',
  'FMIPA - Geologi',
  'FMIPA - Kimia',
  'FMIPA - Matematika',
  'FMIPA - Statistika',
  'FT - Arsitektur',
  'FT - Arsitektur Interior',
  'FT - Teknik Biomedis',
  'FT - Teknik Elektro',
  'FT - Teknik Industri',
  'FT - Teknik Kimia',
  'FT - Teknik Komputer',
  'FT - Teknik Lingkungan',
  'FT - Teknik Mesin',
  'FT - Teknik Metalurgi dan Material',
  'FT - Teknik Perkapalan',
  'FT - Teknik Sipil',
  'FT - Teknologi Bioproses',
  'FASILKOM - Ilmu Komputer',
  'FASILKOM - Sistem Informasi',
  'FH - Ilmu Hukum',
  'FEB - Akuntansi',
  'FEB - Bisnis Islam',
  'FEB - Ekonomi Islam',
  'FEB - Ilmu Ekonomi',
  'FEB - Manajemen',
  'FIB - Arkeologi',
  'FIB - Bahasa dan Kebudayaan Korea',
  'FIB - Filsafat',
  'FIB - Ilmu Perpustakaan',
  'FIB - Ilmu Sejarah',
  'FIB - Sastra Arab',
  'FIB - Sastra Belanda',
  'FIB - Sastra Cina',
  'FIB - Sastra Daerah untuk Sastra Jawa',
  'FIB - Sastra Indonesia',
  'FIB - Sastra Inggris',
  'FIB - Sastra Jepang',
  'FIB - Sastra Jerman',
  'FIB - Sastra Prancis',
  'FIB - Sastra Rusia',
  'FPSI - Psikologi',
  'FISIP - Antropologi Sosial',
  'FISIP - Ilmu Hubungan Internasional',
  'FISIP - Ilmu Komunikasi',
  'FISIP - Ilmu Politik',
  'FISIP - Kesejahteraan Sosial',
  'FISIP - Kriminologi',
  'FISIP - Sosiologi',
  'FIA - Administrasi Fiskal',
  'FIA - Administrasi Negara',
  'FIA - Administrasi Niaga',
];
